seed: 42
test_only: True
accelerator: "cuda"
task: "binary"

data:
  data_dir: "data/paper_data/boxed_png/frame_1_boxed5_bin1"
  train_dir: "data/paper_data/boxed_png/frame_1_boxed5_bin1"
  data_loader: "RawPngLoader"
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  num_workers: 4
  augment: False
  image_size: 256
  labels_file: "test_data.yaml"

wandb:
  project_name: "polarisation_mapping-live"
  run_name: ""
  experiment_id: "1"
  ex_description: "paper_100_labels_binary_algo"

model:
  in_channels: 1
  batch_size: 32
  model_name: "ThreeLayerCnn"
  accuracy_metric: "cross_entropy"

optimizer:
  optimizer: "adamw"
  lr: 0.0004
  weight_decay: 0.002
  momentum: 0.9
  betas: [0.9, 0.999]

scheduler:
  scheduler: "plateau"
  step_size: 30
  step_size_up: 1000
  patience: 2
  factor: 0.5
  min_lr: 3e-5
  max_lr: 5e-5
  T_max: 10
  gamma: 0.1

trainer:
  num_nodes: 1
  devices: 1
  max_epochs: 1000 
  log_dir: "./logs"
  log_every_n_steps: 100
  load_path: ""
  resume_from: False 
  checkpoint_dir: "paper_100_binary/"
  wandb_logging: False

test: 
  load_path: "checkpoints/paper_100_binary/epoch=22-val_loss=0.013500.ckpt"